# Generated by Django 2.1.5 on 2019-02-03 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todostack', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'Priority', 'verbose_name_plural': 'Priorities'},
        ),
    ]
